// <auto-generated />
namespace Battleships.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OnlineBattleAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OnlineBattleAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201905161555028_OnlineBattleAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
